version: '3.5'

services:
  quarkus-service:    
    build: 
      context: . 
      dockerfile: src/main/Docker/Docker.native
    image: docker-database-1:native
    mem_limit: 128m
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://localhost:5432/quarkus-docker
    ports:
      - "8080:8080"
    depends_on:
      quarkus-db:
        condition: service_healthy
    networks:
      - quarkus
      
  quarkus-db:
    image: "postgres:10"
    mem_limit: 128m
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    networks:
      - quarkus
   
networks:
  quarkus:
    driver: bridge
    
  