version: '3.5'

services:
  quarkus-service:    
    build: 
      context: . 
      dockerfile: src/main/Docker/Dockerfile.native
    image: quarkus-db:native
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://host.docker.internal:5434/postgres
    ports:
      - "8080:8080"
    depends_on:
      quarkus-db:
        condition: service_healthy
    networks:
      - quarkus
      
  quarkus-db:
    image: "postgres:latest"
    volumes:
    - ./postgres/:/var/lib/posgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quarkus"]
      interval: 40s
      timeout: 40s
      retries: 10
    ports:
      - "5434:5432"
    restart: always
    networks:
      - quarkus  
networks:
  quarkus:
    driver: bridge
    
  
